# Name for your GitHub Actions workflow
name: Build and Push Docker Image (Optimized)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push: # Renamed for clarity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: skoopy365/react2
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}
            type=raw,value=latest
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          # This is still slow, but caching will help a lot.
          # Consider removing linux/arm64 if you don't need it for every build.
         # platforms: linux/amd64,linux/arm64
          push: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable caching for huge performance gains on subsequent runs
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
